### ISSUE TITLE
翻訳エラー:  Ultimate Support , Expert Support は固有名詞にしてください

### ISSUE THREAD

**Issue by khagiwar** [AdobeDocs/support-resources.ja-JP#1]
Issue in ./help/data-sheets/overview.md

[現在の翻訳 #1] 究極のサポート
[期待される翻訳 #1] Ultimate Support
[原文] Ultimate Support

[現在の翻訳 #2] エキスパートサポート
[期待される翻訳 #2] Expert Support
[原文] Expert Support

**Comment by mak-adobe** [comment]
@khagiwar ありがとうございます。G11N-12929 のチケットで対応を開始しました。

**Comment by mak-adobe** [comment]
@khagiwar 修正が完了しました。「Ultimate サポートプラン」「Expertサポートプラン」に統一されました。
